# Generated by Django 5.2.8 on 2025-11-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0003_exercise_creado_por_exercise_es_personalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
