# Generated by Django 5.2.8 on 2025-11-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0004_routine_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspacioDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('gimnasio', 'Gimnasio'), ('cancha', 'Cancha'), ('piscina', 'Piscina'), ('salon', 'Salón'), ('otro', 'Otro')], max_length=100)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('taller', 'Taller'), ('evento', 'Evento'), ('clase', 'Clase'), ('otro', 'Otro')], max_length=50)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='progresslog',
            name='peso_usado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso utilizado en kilogramos', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Días de la semana separados por comas (ej: L,M,J,V)', max_length=50),
        ),
        migrations.AddField(
            model_name='routine',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('personalizada', 'Personalizada')], default='semanal', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='meta_personal',
            field=models.TextField(blank=True, help_text='Metas personales para esta rutina'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('relacionado_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fit.progresslog')),
                ('relacionado_routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fit.routine')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReservaEspacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='fit.espaciodeportivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_reserva', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=5, null=True)),
                ('altura_cm', models.PositiveIntegerField(blank=True, help_text='Altura en centímetros', null=True)),
                ('condiciones_medicas', models.TextField(blank=True, help_text='Condiciones médicas o lesiones conocidas')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('asistio', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='fit.eventoinstitucional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_inscritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'evento')},
            },
        ),
    ]
