# Generated by Django 5.2.8 on 2025-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0005_espaciodeportivo_eventoinstitucional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='contraindicaciones',
            field=models.TextField(blank=True, help_text='Contraindicaciones médicas o situaciones donde no se debe realizar'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipamiento_necesario',
            field=models.CharField(blank=True, help_text='Equipamiento necesario (separado por comas)', max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instrucciones_paso_a_paso',
            field=models.TextField(blank=True, help_text='Instrucciones detalladas paso a paso para realizar el ejercicio'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='musculos_involucrados',
            field=models.CharField(blank=True, help_text='Músculos principales involucrados (separados por comas)', max_length=500),
        ),
        migrations.AddField(
            model_name='exercise',
            name='precauciones',
            field=models.TextField(blank=True, help_text='Precauciones importantes al realizar este ejercicio'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='variaciones',
            field=models.TextField(blank=True, help_text='Variaciones del ejercicio (principiante, intermedio, avanzado)'),
        ),
    ]
